#!/usr/bin/env bash
# Install the Familiar's engine as a systemd --user service.
#
#   scripts/install.sh [--check] [--repo DIR]
#
# --check   dry-run: print every action it WOULD take, change nothing
# --repo    repo root (default: this script's parent — only needed when
#           invoking the script from a copy outside the repo)
#
# Default flow: clone at ~/muse-familiar and `systemctl --user link` the
# repo's unit (single source, no copies). Any other location gets a drop-in
# that resets and re-sets the unit's path-bearing directives (systemd
# drop-ins APPEND to list directives, so each needs an empty reset line
# first). Generates the webhook key (0600) if absent. Restarts the service
# only when the link, drop-in, or key actually changed.
#
# Headless boards (SSH sessions that log out): the user manager stops with
# the last session unless lingering is on — run once:
#   sudo loginctl enable-linger $USER

set -euo pipefail

fail() { echo "BLOCKED: $*" >&2; exit 1; }
say()  { echo "install.sh: $*"; }

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CHECK=0
while [ $# -gt 0 ]; do
    case "$1" in
        --check) CHECK=1 ;;
        --repo)  [ $# -ge 2 ] || fail "--repo needs a value"; REPO="$(cd "$2" && pwd)"; shift ;;
        --repo=*) REPO="$(cd "${1#--repo=}" && pwd)" ;;
        *) echo "unknown option: $1 (usage: $0 [--check] [--repo DIR])" >&2; exit 3 ;;
    esac
    shift
done

UNIT_SRC="$REPO/units/familiar-engine.service"
UNIT_NAME="familiar-engine"
USER_UNITS="$HOME/.config/systemd/user"
UNIT_LINK="$USER_UNITS/$UNIT_NAME.service"
DROPIN_DIR="$USER_UNITS/$UNIT_NAME.service.d"
DROPIN="$DROPIN_DIR/override.conf"
KEY_FILE="$HOME/.config/familiar/key"
UV_BIN="$(command -v uv || true)"; UV_BIN="${UV_BIN:-$HOME/.local/bin/uv}"

[ -f "$UNIT_SRC" ] || fail "unit template not found: $UNIT_SRC"
[ -x "$UV_BIN" ]   || fail "uv not found at $UV_BIN (install: https://docs.astral.sh/uv/)"
case "$REPO$UV_BIN" in *[[:space:]]*)
    fail "paths with whitespace/newlines would corrupt the generated unit — move the repo or uv";; esac

dropin_content() {
    cat <<EOF
# Generated by scripts/install.sh — repo lives outside ~/muse-familiar.
# Reset lines are required: drop-ins APPEND to list directives.
[Service]
ExecStartPre=
ExecStartPre=$REPO/units/ntp_gate.sh
Environment=
Environment=PYTHONPATH=$REPO
ExecStart=
ExecStart=$UV_BIN run --with msgpack --directory $REPO python3 -m familiar.engine --key-file $KEY_FILE
ExecStopPost=
ExecStopPost=$REPO/units/display_reset.sh
EOF
}

# ---------------------------------------------------------------- plan ----
ACTIONS=()
DROPIN_NEEDED=0
DROPIN_CHANGED=0
if [ "$REPO" = "$HOME/muse-familiar" ]; then
    ACTIONS+=("link $UNIT_SRC -> $UNIT_LINK (unit paths already match this location)")
else
    DROPIN_NEEDED=1
    if [ ! -f "$DROPIN" ] || [ "$(dropin_content)" != "$(cat "$DROPIN")" ]; then
        DROPIN_CHANGED=1
        ACTIONS+=("write $DROPIN resetting+re-setting ExecStartPre/Environment/ExecStart/ExecStopPost to $REPO")
    else
        ACTIONS+=("drop-in already current: $DROPIN")
    fi
fi
KEY_CREATED=0
if [ ! -f "$KEY_FILE" ]; then
    KEY_CREATED=1
    ACTIONS+=("generate $KEY_FILE (24 random bytes, mode 0600)")
fi
LINK_NOW=0
if [ ! -e "$UNIT_LINK" ] || \
   [ "$(readlink -f "$UNIT_LINK" 2>/dev/null || true)" != "$(readlink -f "$UNIT_SRC")" ]; then
    LINK_NOW=1
    ACTIONS+=("systemctl --user link $UNIT_SRC")
fi

# Restart only when something actually changed (a no-op re-run must not
# bounce a healthy engine).
RESTART=0
[ "$LINK_NOW" = 1 ] || [ "$KEY_CREATED" = 1 ] || [ "$DROPIN_CHANGED" = 1 ] && RESTART=1

if [ "$CHECK" = 1 ]; then
    say "dry run — actions for install at $REPO:"
    [ ${#ACTIONS[@]} -eq 0 ] && say "  (nothing to change — already installed)"
    for a in "${ACTIONS[@]}"; do say "  - $a"; done
    if [ "$DROPIN_NEEDED" = 1 ]; then
        say "exact drop-in content ($DROPIN):"
        dropin_content | sed 's/^/    /'
    fi
    [ "$RESTART" = 1 ] && say "  - systemctl --user daemon-reload; enable --now $UNIT_NAME; restart" \
                       || say "  - systemctl --user enable --now $UNIT_NAME (no restart needed)"
    [ "$(loginctl show-user "$USER" --value -p Linger 2>/dev/null || echo no)" = "yes" ] \
        || say "note: lingering is OFF — on a headless board run: sudo loginctl enable-linger \$USER"
    say "READY"
    exit 0
fi

# -------------------------------------------------------------- execute ----
mkdir -p "$USER_UNITS" "$(dirname "$KEY_FILE")"

if [ "$DROPIN_NEEDED" = 1 ] && [ "$DROPIN_CHANGED" = 1 ]; then
    mkdir -p "$DROPIN_DIR"
    dropin_content > "$DROPIN"
    say "wrote $DROPIN"
elif [ "$DROPIN_NEEDED" = 1 ]; then
    say "drop-in already current: $DROPIN"
fi

if [ ! -e "$UNIT_LINK" ] || [ "$(readlink -f "$UNIT_LINK" 2>/dev/null || true)" != "$(readlink -f "$UNIT_SRC")" ]; then
    systemctl --user link "$UNIT_SRC"
    say "linked $UNIT_SRC"
fi

if [ "$KEY_CREATED" = 1 ]; then
    (umask 177; head -c24 /dev/urandom | base64 > "$KEY_FILE")
    chmod 600 "$KEY_FILE"
    say "generated $KEY_FILE"
fi

systemctl --user daemon-reload
systemctl --user enable --now "$UNIT_NAME" >/dev/null
if [ "$RESTART" = 1 ] && systemctl --user is-active --quiet "$UNIT_NAME"; then
    systemctl --user restart "$UNIT_NAME"
    say "restarted $UNIT_NAME (config changed)"
else
    say "enabled $UNIT_NAME"
fi
systemctl --user --no-pager --lines=0 status "$UNIT_NAME" >/dev/null 2>&1 || true
say "done — check with: systemctl --user is-active $UNIT_NAME  (or: python3 -m familiar.cli status)"
